### ISSUE TITLE
Wildcard Support for Fault Injection Configuration

### ISSUE THREAD

**Issue by Natnael-Getachew-Yirga** [dsrhaslab/lazyfs#10]
I'm using LazyFS for fault injection, but I need to target files where the names aren’t known in advance. It would be great if I could use a wildcard (e.g., `*.txt`) in the configuration instead of specifying exact file names. Right now, trying to add faults after files are created hasn’t worked.

### Example Configuration
Current setup:
```toml
[[injection]]
type="torn-op"
file="output1.txt"
occurrence=5
parts=3 # or parts_bytes=[4096,3600,1260]
persist=[1,3]
```
What I would like to use:
```toml
[[injection]]
type="torn-op"
file="*.txt"
occurrence=5
parts=3 # or parts_bytes=[4096,3600,1260]
persist=[1,3]
```

### Feature Request

Please add wildcard support (like `*`)for the `file` field to make fault injection work with dynamic file names.

### Expected Behavior

- Applying fault rules to any file that matches a wildcard (e.g., `*.txt`).

If there’s a workaround I may have missed, I would greatly appreciate your guidance. Thank you for your time and consideration!
